Function Get-StockFundamentalData
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)][String]$Symbol,
        [Parameter(Mandatory)]
            [ValidateSet("IncomeStatement","BalanceSheet","CashFlowStatement")][String[]]$Report
        # [Parameter()][ValidateSet("Quarter","Annual")]$Period = "Quarter"
    )

    BEGIN
    {
        [System.Collections.ArrayList]$output = @()

        $uriPrefix = `
            "https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/premium/timeseries/$Symbol`?lang=en-US&region=US&symbol=$Symbol`&padTimeSeries=true&type="
        $uriSuffix = "&merge=false&period1=&period2=1691511894&corsDomain=finance.yahoo.com"

        ### Forcing to "quarterly" for now.  Having "annual" as an option could lead to mixing in the database.
        ### Annual and TTM values can be derived from the quarters in SQL or Power BI.
        ### Leaving the options in code in case a suitable need arises to choose a frequency.
        # $frequency = switch ($Period)
        # {
        #     "Quarter" { "quarterly" }
        #     "Annual" { "annual" }
        # }

        $frequency = "quarterly"

        $income = @(
            "TotalRevenue"
            #"OperatingRevenue"
            "CostOfRevenue"
            "GrossProfit"
            "OperatingExpense"
            # "SellingGeneralAndAdministration"
            # "ResearchAndDevelopment"
            # "OtherOperatingExpenses"
            "OperatingIncome"
            "PretaxIncome"
            "TaxProvision"
            "NetIncome"
            "BasicAverageShares"
            "DilutedAverageShares"
            "BasicEPS"
            "DilutedEPS"
        
            # "NetNonOperatingInterestIncomeExpense"
            # "InterestIncomeNonOperating"
            # "InterestExpenseNonOperating"
            # "OtherIncomeExpense"
            # "GainOnSaleOfSecurity"
            # "EarningsFromEquityInterest"
            # "SpecialIncomeCharges"
            # "RestructuringAndMergernAcquisition"
        )

        # $income = @(
        #     "TaxEffectOfUnusualItems"
        #     "TaxRateForCalcs"
        #     "NormalizedEBITDA"
        #     "NormalizedDilutedEPS"
        #     "NormalizedBasicEPS"
        #     "TotalUnusualItems"
        #     "TotalUnusualItemsExcludingGoodwill"
        #     "NetIncomeFromContinuingOperationNetMinorityInterest"
        #     "ReconciledDepreciation"
        #     "ReconciledCostOfRevenue"
        #     "EBITDA"
        #     "EBIT"
        #     "NetInterestIncome"
        #     "InterestExpense"
        #     "InterestIncome"
        #     "ContinuingAndDiscontinuedDilutedEPS"
        #     "ContinuingAndDiscontinuedBasicEPS"
        #     "NormalizedIncome"
        #     "NetIncomeFromContinuingAndDiscontinuedOperation"
        #     "TotalExpenses"
        #     "RentExpenseSupplemental"
        #     "ReportedNormalizedDilutedEPS"
        #     "ReportedNormalizedBasicEPS"
        #     "TotalOperatingIncomeAsReported"
        #     "DividendPerShare"
        #     "DilutedAverageShares"
        #     "BasicAverageShares"
        #     "DilutedEPS"
        #     "DilutedEPSOtherGainsLosses"
        #     "TaxLossCarryforwardDilutedEPS"
        #     "DilutedAccountingChange"
        #     "DilutedExtraordinary"
        #     "DilutedDiscontinuousOperations"
        #     "DilutedContinuousOperations"
        #     "BasicEPS"
        #     "BasicEPSOtherGainsLosses"
        #     "TaxLossCarryforwardBasicEPS"
        #     "BasicAccountingChange"
        #     "BasicExtraordinary"
        #     "BasicDiscontinuousOperations"
        #     "BasicContinuousOperations"
        #     "DilutedNIAvailtoComStockholders"
        #     "AverageDilutionEarnings"
        #     "NetIncomeCommonStockholders"
        #     "OtherunderPreferredStockDividend"
        #     "PreferredStockDividends"
        #     "NetIncome"
        #     "MinorityInterests"
        #     "NetIncomeIncludingNoncontrollingInterests"
        #     "NetIncomeFromTaxLossCarryforward"
        #     "NetIncomeExtraordinary"
        #     "NetIncomeDiscontinuousOperations"
        #     "NetIncomeContinuousOperations"
        #     "EarningsFromEquityInterestNetOfTax"
        #     "TaxProvision"
        #     "PretaxIncome"
        #     "OtherIncomeExpense"
        #     "OtherNonOperatingIncomeExpenses"
        #     "SpecialIncomeCharges"
        #     "GainOnSaleOfPPE"
        #     "GainOnSaleOfBusiness"
        #     "OtherSpecialCharges"
        #     "WriteOff"
        #     "ImpairmentOfCapitalAssets"
        #     "RestructuringAndMergernAcquisition"
        #     "SecuritiesAmortization"
        #     "EarningsFromEquityInterest"
        #     "GainOnSaleOfSecurity"
        #     "NetNonOperatingInterestIncomeExpense"
        #     "TotalOtherFinanceCost"
        #     "InterestExpenseNonOperating"
        #     "InterestIncomeNonOperating"
        #     "OperatingIncome"
        #     "OperatingExpense"
        #     "OtherOperatingExpenses"
        #     "OtherTaxes"
        #     "ProvisionForDoubtfulAccounts"
        #     "DepreciationAmortizationDepletionIncomeStatement"
        #     "DepletionIncomeStatement"
        #     "DepreciationAndAmortizationInIncomeStatement"
        #     "Amortization"
        #     "AmortizationOfIntangiblesIncomeStatement"
        #     "DepreciationIncomeStatement"
        #     "ResearchAndDevelopment"
        #     "SellingGeneralAndAdministration"
        #     "SellingAndMarketingExpense"
        #     "GeneralAndAdministrativeExpense"
        #     "OtherGandA"
        #     "InsuranceAndClaims"
        #     "RentAndLandingFees"
        #     "SalariesAndWages"
        #     "GrossProfit"
        #     "CostOfRevenue"
        #     "TotalRevenue"
        #     "ExciseTaxes"
        #     "OperatingRevenue"
        # )

        $balance = @(
            "TotalAssets"
            "CurrentAssets"
            "CashCashEquivalentsAndShortTermInvestments"
            "CashAndCashEquivalents"
            "CashFinancial"
            "CashEquivalents"
            "OtherShortTermInvestments"
            "Receivables"
            "GrossAccountsReceivable"
            "AllowanceForDoubtfulAccountsReceivable"
            "Inventory"
            "RawMaterials"
            "WorkInProcess"
            "FinishedGoods"
            "CurrentDeferredAssets"
            "CurrentDeferredTaxesAssets"
            "HedgingAssetsCurrent"
            "OtherCurrentAssets"
            
        )

        $balance = @(
            "PreferredSharesNumber"
            "OrdinarySharesNumber"
            "ShareIssued"
            "NetDebt"
            "TotalDebt"
            "TangibleBookValue"
            "InvestedCapital"
            "WorkingCapital"
            "NetTangibleAssets"
            "CapitalLeaseObligations"
            "CommonStockEquity"
            "PreferredStockEquity"
            "TotalCapitalization"
            "TotalEquityGrossMinorityInterest"
            "MinorityInterest"
            "StockholdersEquity"
            "OtherEquityInterest"
            "GainsLossesNotAffectingRetainedEarnings"
            "OtherEquityAdjustments"
            "FixedAssetsRevaluationReserve"
            "ForeignCurrencyTranslationAdjustments"
            "MinimumPensionLiabilities"
            "UnrealizedGainLoss"
            "TreasuryStock"
            "RetainedEarnings"
            "AdditionalPaidInCapital"
            "CapitalStock"
            "OtherCapitalStock"
            "CommonStock"
            "PreferredStock"
            "TotalPartnershipCapital"
            "GeneralPartnershipCapital"
            "LimitedPartnershipCapital"
            "TotalLiabilitiesNetMinorityInterest"
            "TotalNonCurrentLiabilitiesNetMinorityInterest"
            "OtherNonCurrentLiabilities"
            "LiabilitiesHeldforSaleNonCurrent"
            "RestrictedCommonStock"
            "PreferredSecuritiesOutsideStockEquity"
            "DerivativeProductLiabilities"
            "EmployeeBenefits"
            "NonCurrentPensionAndOtherPostretirementBenefitPlans"
            "NonCurrentAccruedExpenses"
            "DuetoRelatedPartiesNonCurrent"
            "TradeandOtherPayablesNonCurrent"
            "NonCurrentDeferredLiabilities"
            "NonCurrentDeferredRevenue"
            "NonCurrentDeferredTaxesLiabilities"
            "LongTermDebtAndCapitalLeaseObligation"
            "LongTermCapitalLeaseObligation"
            "LongTermDebt"
            "LongTermProvisions"
            "CurrentLiabilities"
            "OtherCurrentLiabilities"
            "CurrentDeferredLiabilities"
            "CurrentDeferredRevenue"
            "CurrentDeferredTaxesLiabilities"
            "CurrentDebtAndCapitalLeaseObligation"
            "CurrentCapitalLeaseObligation"
            "CurrentDebt"
            "OtherCurrentBorrowings"
            "LineOfCredit"
            "CommercialPaper"
            "CurrentNotesPayable"
            "PensionandOtherPostRetirementBenefitPlansCurrent"
            "CurrentProvisions"
            "PayablesAndAccruedExpenses"
            "CurrentAccruedExpenses"
            "InterestPayable"
            "Payables"
            "OtherPayable"
            "DuetoRelatedPartiesCurrent"
            "DividendsPayable"
            "TotalTaxPayable"
            "IncomeTaxPayable"
            "AccountsPayable"
            "TotalAssets"
            "TotalNonCurrentAssets"
            "OtherNonCurrentAssets"
            "DefinedPensionBenefit"
            "NonCurrentPrepaidAssets"
            "NonCurrentDeferredAssets"
            "NonCurrentDeferredTaxesAssets"
            "DuefromRelatedPartiesNonCurrent"
            "NonCurrentNoteReceivables"
            "NonCurrentAccountsReceivable"
            "FinancialAssets"
            "InvestmentsAndAdvances"
            "OtherInvestments"
            "InvestmentinFinancialAssets"
            "HeldToMaturitySecurities"
            "AvailableForSaleSecurities"
            "FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal"
            "TradingSecurities"
            "LongTermEquityInvestment"
            "InvestmentsinJointVenturesatCost"
            "InvestmentsInOtherVenturesUnderEquityMethod"
            "InvestmentsinAssociatesatCost"
            "InvestmentsinSubsidiariesatCost"
            "InvestmentProperties"
            "GoodwillAndOtherIntangibleAssets"
            "OtherIntangibleAssets"
            "Goodwill"
            "NetPPE"
            "AccumulatedDepreciation"
            "GrossPPE"
            "Leases"
            "ConstructionInProgress"
            "OtherProperties"
            "MachineryFurnitureEquipment"
            "BuildingsAndImprovements"
            "LandAndImprovements"
            "Properties"
            "CurrentAssets"
            "OtherCurrentAssets"
            "HedgingAssetsCurrent"
            "AssetsHeldForSaleCurrent"
            "CurrentDeferredAssets"
            "CurrentDeferredTaxesAssets"
            "RestrictedCash"
            "PrepaidAssets"
            "Inventory"
            "InventoriesAdjustmentsAllowances"
            "OtherInventories"
            "FinishedGoods"
            "WorkInProcess"
            "RawMaterials"
            "Receivables"
            "ReceivablesAdjustmentsAllowances"
            "OtherReceivables"
            "DuefromRelatedPartiesCurrent"
            "TaxesReceivable"
            "AccruedInterestReceivable"
            "NotesReceivable"
            "LoansReceivable"
            "AccountsReceivable"
            "AllowanceForDoubtfulAccountsReceivable"
            "GrossAccountsReceivable"
            "CashCashEquivalentsAndShortTermInvestments"
            "OtherShortTermInvestments"
            "CashAndCashEquivalents"
            "CashEquivalents"
            "CashFinancial"
        )

        $cash = @(
            "DomesticSales"
            "AdjustedGeographySegmentData"
            "FreeCashFlow"
            "RepurchaseOfCapitalStock"
            "RepaymentOfDebt"
            "IssuanceOfDebt"
            "IssuanceOfCapitalStock"
            "CapitalExpenditure"
            "InterestPaidSupplementalData"
            "IncomeTaxPaidSupplementalData"
            "EndCashPosition"
            "OtherCashAdjustmentOutsideChangeinCash"
            "BeginningCashPosition"
            "EffectOfExchangeRateChanges"
            "ChangesInCash"
            "OtherCashAdjustmentInsideChangeinCash"
            "CashFlowFromDiscontinuedOperation"
            "FinancingCashFlow"
            "CashFromDiscontinuedFinancingActivities"
            "CashFlowFromContinuingFinancingActivities"
            "NetOtherFinancingCharges"
            "InterestPaidCFF"
            "ProceedsFromStockOptionExercised"
            "CashDividendsPaid"
            "PreferredStockDividendPaid"
            "CommonStockDividendPaid"
            "NetPreferredStockIssuance"
            "PreferredStockPayments"
            "PreferredStockIssuance"
            "NetCommonStockIssuance"
            "CommonStockPayments"
            "CommonStockIssuance"
            "NetIssuancePaymentsOfDebt"
            "NetShortTermDebtIssuance"
            "ShortTermDebtPayments"
            "ShortTermDebtIssuance"
            "NetLongTermDebtIssuance"
            "LongTermDebtPayments"
            "LongTermDebtIssuance"
            "InvestingCashFlow"
            "CashFromDiscontinuedInvestingActivities"
            "CashFlowFromContinuingInvestingActivities"
            "NetOtherInvestingChanges"
            "InterestReceivedCFI"
            "DividendsReceivedCFI"
            "NetInvestmentPurchaseAndSale"
            "SaleOfInvestment"
            "PurchaseOfInvestment"
            "NetInvestmentPropertiesPurchaseAndSale"
            "SaleOfInvestmentProperties"
            "PurchaseOfInvestmentProperties"
            "NetBusinessPurchaseAndSale"
            "SaleOfBusiness"
            "PurchaseOfBusiness"
            "NetIntangiblesPurchaseAndSale"
            "SaleOfIntangibles"
            "PurchaseOfIntangibles"
            "NetPPEPurchaseAndSale"
            "SaleOfPPE"
            "PurchaseOfPPE"
            "CapitalExpenditureReported"
            "OperatingCashFlow"
            "CashFromDiscontinuedOperatingActivities"
            "CashFlowFromContinuingOperatingActivities"
            "TaxesRefundPaid"
            "InterestReceivedCFO"
            "InterestPaidCFO"
            "DividendReceivedCFO"
            "DividendPaidCFO"
            "ChangeInWorkingCapital"
            "ChangeInOtherWorkingCapital"
            "ChangeInOtherCurrentLiabilities"
            "ChangeInOtherCurrentAssets"
            "ChangeInPayablesAndAccruedExpense"
            "ChangeInAccruedExpense"
            "ChangeInInterestPayable"
            "ChangeInPayable"
            "ChangeInDividendPayable"
            "ChangeInAccountPayable"
            "ChangeInTaxPayable"
            "ChangeInIncomeTaxPayable"
            "ChangeInPrepaidAssets"
            "ChangeInInventory"
            "ChangeInReceivables"
            "ChangesInAccountReceivables"
            "OtherNonCashItems"
            "ExcessTaxBenefitFromStockBasedCompensation"
            "StockBasedCompensation"
            "UnrealizedGainLossOnInvestmentSecurities"
            "ProvisionandWriteOffofAssets"
            "AssetImpairmentCharge"
            "AmortizationOfSecurities"
            "DeferredTax"
            "DeferredIncomeTax"
            "DepreciationAmortizationDepletion"
            "Depletion"
            "DepreciationAndAmortization"
            "AmortizationCashFlow"
            "AmortizationOfIntangibles"
            "Depreciation"
            "OperatingGainsLosses"
            "PensionAndEmployeeBenefitExpense"
            "EarningsLossesFromEquityInvestments"
            "GainLossOnInvestmentSecurities"
            "NetForeignCurrencyExchangeGainLoss"
            "GainLossOnSaleOfPPE"
            "GainLossOnSaleOfBusiness"
            "NetIncomeFromContinuingOperations"
            "CashFlowsfromusedinOperatingActivitiesDirect"
            "TaxesRefundPaidDirect"
            "InterestReceivedDirect"
            "InterestPaidDirect"
            "DividendsReceivedDirect"
            "DividendsPaidDirect"
            "ClassesofCashPayments"
            "OtherCashPaymentsfromOperatingActivities"
            "PaymentsonBehalfofEmployees"
            "PaymentstoSuppliersforGoodsandServices"
            "ClassesofCashReceiptsfromOperatingActivities"
            "OtherCashReceiptsfromOperatingActivities"
            "ReceiptsfromGovernmentGrants"
            "ReceiptsfromCustomers"
        )
    }

    PROCESS
    {
        foreach ($q in $Report)
        {
            $body = switch($q)
            {
                "IncomeStatement" { $income; break }
                "BalanceSheet" { $balance; break }
                "CashFlowStatement" { $cash; break }
            }
    
            ### Session uses a persistent cookie for Yahoo Finance access, see CoreData.ps1 for info
            $data = (Invoke-RestMethod -Method GET -WebSession $Script:yahoo `
                -Uri ($uriPrefix + (($body | ForEach-Object { "$frequency$_" }) -join "%2C") + $uriSuffix)).timeseries.result
            
            $dates = $data[0].timestamp | ForEach-Object { [System.DateTimeOffset]::FromUnixTimeSeconds($_).Date.ToString("yyyy-MM-dd") }
    
            for ($a = 0; $a -lt $dates.Count; $a++)
            {
                $temp = [ordered]@{"StockSymbol" = $Symbol; "ReportDate" = $dates[$a]}
    
                foreach ($x in $body)
                {
                   try { $temp.Add($x,$data[$data.meta.type.IndexOf("quarterly$x")]."quarterly$x"[$a].reportedValue.raw) }
                   catch { $temp.Add($x,$null) }
                }
    
                [void]$output.Add([PSCustomObject]$temp)
            }
        }

        return $output
    }
}


