USE [BULKDATA]
GO

CREATE TABLE [dbo].[SHORT_INTEREST_SCHEDULE] (
	[SettlementDate] DATE NOT NULL
	,[PublishDate] DATE NOT NULL

	CONSTRAINT [PK_SHORT_INTEREST_SCHEDULE] PRIMARY KEY CLUSTERED ([SettlementDate],[PublishDate] ASC)
)
GO

CREATE TABLE [dbo].[SHORT_INTEREST] (
	[Symbol] VARCHAR(12) NOT NULL
	,[SettlementDate] DATE NOT NULL
	,[DaysToCover] DECIMAL(5,2) NOT NULL
	,[AvgDailyVolume] BIGINT NOT NULL
	,[CurrentShortQty] BIGINT NOT NULL
	,[PreviousShortQty] BIGINT NOT NULL
	,[ChangePercent] DECIMAL(13,2) NOT NULL
	,[ChangeShortQty] BIGINT NOT NULL
 
    CONSTRAINT [PK_SHORT_INTEREST] PRIMARY KEY CLUSTERED ([Symbol],[SettlementDate] ASC)
)
GO

CREATE TABLE [dbo].[SEC_FILING_CIK] (
	[CIKID] INT IDENTITY(1,1) NOT NULL,
	[CIK] CHAR(10) NOT NULL

	CONSTRAINT [PK_SEC_FILING_CIK] PRIMARY KEY CLUSTERED ([CIKID] ASC)
	,CONSTRAINT [UQ_SEC_FILING_CIK] UNIQUE ([CIK])
)
GO

CREATE TABLE [dbo].[SEC_FILING_FORM] (
    [FormID] SMALLINT NOT NULL
    ,[FormType] VARCHAR(20) NOT NULL
    ,[FormDescription] VARCHAR(150) NULL

    CONSTRAINT [PK_SEC_FILING_FORM] PRIMARY KEY CLUSTERED ([FormID] ASC)
    ,CONSTRAINT [UQ_SEC_FILING_FORM] UNIQUE ([FormType])
)
GO

CREATE TABLE [dbo].[SEC_FILING_INDEX] (
	[DateFiled] DATE NOT NULL,
	[CIKID] INT NOT NULL,
	[FormID] SMALLINT NOT NULL,
	[FileName] VARCHAR(45) NOT NULL,

    CONSTRAINT [PK_SEC_FILING_INDEX] PRIMARY KEY CLUSTERED ([DateFiled],[CIKID],[FormID],[FileName] ASC)
    ,CONSTRAINT [FK_SEC_FILING_INDEX_CikID] FOREIGN KEY([CIKID]) REFERENCES [SEC_FILING_CIK]([CIKID])
    ,CONSTRAINT [FK_SEC_FILING_INDEX_FormID] FOREIGN KEY([FormID]) REFERENCES [SEC_FILING_FORM]([FormID])
)
GO