USE [FINDATA]
GO

-------------------------------------------------------------------------------------------------
-- Stock Classification by Sector, Group, Industry, and Sub-Industry
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Stock_Classification]
AS
    SELECT 
	[StockSymbol] AS [Symbol]
	,[StockName] AS [Name]
	,(SELECT [GicsLabel] FROM [dbo].[GICS] WHERE ([GicsNode] = ([dbo].[Stock].[GICS]).GetAncestor(3))) AS [Sector]
	,(SELECT [GicsLabel] FROM [dbo].[GICS] WHERE ([GicsNode] = ([dbo].[Stock].[GICS]).GetAncestor(2))) AS [Group]
	,(SELECT [GicsLabel] FROM [dbo].[GICS] WHERE ([GicsNode] = ([dbo].[Stock].[GICS]).GetAncestor(1))) AS [Industry]
	,(SELECT [GicsLabel] FROM [dbo].[GICS] WHERE ([GicsNode] = ([dbo].[Stock].[GICS]).GetAncestor(0))) AS [SubIndustry]
	FROM [dbo].[Stock]
GO

-------------------------------------------------------------------------------------------------
-- Find any stocks that have NULL values for Pricing Data
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Null_Price_Data]
AS
	SELECT
	[stk].[StockSymbol]
	,[stk].[StockName]
	,[dbo].[PRICE_HISTORY].[PriceDate]
	,[dbo].[PRICE_HISTORY].[HighPrice]
	,[dbo].[PRICE_HISTORY].[LowPrice]
	,[dbo].[PRICE_HISTORY].[ClosePrice]
	,[dbo].[PRICE_HISTORY].[AdjClosePrice]
	,[dbo].[PRICE_HISTORY].[Volume]
	FROM [dbo].[STOCK] AS [stk]
	INNER JOIN [dbo].[PRICE_HISTORY] ON [stk].[StockID] = dbo.[PRICE_HISTORY].[StockID]
	WHERE ([dbo].[PRICE_HISTORY].[ClosePrice] IS NULL)
GO

-------------------------------------------------------------------------------------------------
-- View Volume by Sector per Date
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Volume_By_Sector_By_Date]
AS
	SELECT
	[class].[Sector]
	,[price].[PriceDate]
	,SUM([price].[Volume]) AS DailyVolume
	FROM [dbo].[vw_Stock_Classification] [class]
	INNER JOIN [dbo].[STOCK] [stk] ON [class].[Symbol] = [stk].[StockSymbol]
	INNER JOIN [dbo].[PRICE_HISTORY] AS [price] ON [price].[StockID] = [stk].[StockID]
	GROUP BY [class].[Sector], [price].[PriceDate]
GO

-------------------------------------------------------------------------------------------------
-- View SEC Filing Information
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_SEC_Filing]
AS
	SELECT [stk].[StockSymbol]
	,[sec].[DateFiled]
	,[frm].[FormType]
	,[frm].[FormDescription]
	,[sec].[FileName] AS [FilingIdent]
	FROM [dbo].[STOCK] [stk]
	INNER JOIN [dbo].[SEC_FILING_INDEX] [sec] ON [stk].[StockID] = [sec].[StockID]
	INNER JOIN [dbo].[SEC_FILING_FORM] [frm] ON [sec].[FormID] = [frm].[FormID]
GO

-------------------------------------------------------------------------------------------------
-- Income Statement
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Income_Statement]
AS
	SELECT [stk].[StockSymbol]
		,[inc].[ReportDate]
		,[inc].[OperatingRevenue]
		,[inc].[ExciseTaxes]
		,[inc].[TotalRevenue]
		,[inc].[CostOfRevenue]
		,[inc].[GrossProfit]
		,[inc].[SalariesAndWages]
		,[inc].[RentAndLandingFees]
		,[inc].[InsuranceAndClaims]
		,[inc].[OtherGandA]
		,[inc].[GeneralAndAdministrativeExpense]
		,[inc].[SellingAndMarketingExpense]
		,[inc].[SellingGeneralAndAdministration]
		,[inc].[ResearchAndDevelopment]
		,[inc].[DepreciationIncomeStatement]
		,[inc].[AmortizationOfIntangiblesIncomeStatement]
		,[inc].[Amortization]
		,[inc].[DepreciationAndAmortizationInIncomeStatement]
		,[inc].[DepletionIncomeStatement]
		,[inc].[DepreciationAmortizationDepletionIncomeStatement]
		,[inc].[ProvisionForDoubtfulAccounts]
		,[inc].[OtherTaxes]
		,[inc].[OtherOperatingExpenses]
		,[inc].[OperatingExpense]
		,[inc].[OperatingIncome]
		,[inc].[InterestIncomeNonOperating]
		,[inc].[InterestExpenseNonOperating]
		,[inc].[TotalOtherFinanceCost]
		,[inc].[NetNonOperatingInterestIncomeExpense]
		,[inc].[GainOnSaleOfSecurity]
		,[inc].[EarningsFromEquityInterest]
		,[inc].[SecuritiesAmortization]
		,[inc].[RestructuringAndMergernAcquisition]
		,[inc].[ImpairmentOfCapitalAssets]
		,[inc].[WriteOff]
		,[inc].[OtherSpecialCharges]
		,[inc].[GainOnSaleOfBusiness]
		,[inc].[GainOnSaleOfPPE]
		,[inc].[SpecialIncomeCharges]
		,[inc].[OtherNonOperatingIncomeExpenses]
		,[inc].[OtherIncomeExpense]
		,[inc].[PretaxIncome]
		,[inc].[TaxProvision]
		,[inc].[EarningsFromEquityInterestNetOfTax]
		,[inc].[NetIncomeContinuousOperations]
		,[inc].[NetIncomeDiscontinuousOperations]
		,[inc].[NetIncomeExtraordinary]
		,[inc].[NetIncomeFromTaxLossCarryforward]
		,[inc].[NetIncomeIncludingNoncontrollingInterests]
		,[inc].[MinorityInterests]
		,[inc].[NetIncome]
		,[inc].[PreferredStockDividends]
		,[inc].[OtherunderPreferredStockDividend]
		,[inc].[NetIncomeCommonStockholders]
		,[inc].[AverageDilutionEarnings]
		,[inc].[DilutedNIAvailtoComStockholders]
		,[inc].[BasicContinuousOperations]
		,[inc].[BasicDiscontinuousOperations]
		,[inc].[BasicExtraordinary]
		,[inc].[BasicAccountingChange]
		,[inc].[TaxLossCarryforwardBasicEPS]
		,[inc].[BasicEPSOtherGainsLosses]
		,[inc].[BasicEPS]
		,[inc].[DilutedContinuousOperations]
		,[inc].[DilutedDiscontinuousOperations]
		,[inc].[DilutedExtraordinary]
		,[inc].[DilutedAccountingChange]
		,[inc].[TaxLossCarryforwardDilutedEPS]
		,[inc].[DilutedEPSOtherGainsLosses]
		,[inc].[DilutedEPS]
		,[inc].[BasicAverageShares]
		,[inc].[DilutedAverageShares]
		,[inc].[DividendPerShare]
		,[inc].[TotalOperatingIncomeAsReported]
		,[inc].[ReportedNormalizedBasicEPS]
		,[inc].[ReportedNormalizedDilutedEPS]
		,[inc].[RentExpenseSupplemental]
		,[inc].[TotalExpenses]
		,[inc].[NetIncomeFromContinuingAndDiscontinuedOperation]
		,[inc].[NormalizedIncome]
		,[inc].[ContinuingAndDiscontinuedBasicEPS]
		,[inc].[ContinuingAndDiscontinuedDilutedEPS]
		,[inc].[InterestIncome]
		,[inc].[InterestExpense]
		,[inc].[NetInterestIncome]
		,[inc].[EBIT]
		,[inc].[EBITDA]
		,[inc].[ReconciledCostOfRevenue]
		,[inc].[ReconciledDepreciation]
		,[inc].[NetIncomeFromContinuingOperationNetMinorityInterest]
		,[inc].[TotalUnusualItemsExcludingGoodwill]
		,[inc].[TotalUnusualItems]
		,[inc].[NormalizedBasicEPS]
		,[inc].[NormalizedDilutedEPS]
		,[inc].[NormalizedEBITDA]
		,[inc].[TaxRateForCalcs]
		,[inc].[TaxEffectOfUnusualItems]
	FROM [dbo].[STOCK] [stk]
	INNER JOIN [dbo].[INCOME_STATEMENT] [inc] ON [stk].[StockID] = [inc].[StockID]
GO

-------------------------------------------------------------------------------------------------
-- Balance Sheet
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Balance_Sheet]
AS
	SELECT [stk].[StockSymbol]
		,[bal].[ReportDate]
		,[bal].[CashFinancial]
		,[bal].[CashEquivalents]
		,[bal].[CashAndCashEquivalents]
		,[bal].[OtherShortTermInvestments]
		,[bal].[CashCashEquivalentsAndShortTermInvestments]
		,[bal].[GrossAccountsReceivable]
		,[bal].[AllowanceForDoubtfulAccountsReceivable]
		,[bal].[AccountsReceivable]
		,[bal].[LoansReceivable]
		,[bal].[NotesReceivable]
		,[bal].[AccruedInterestReceivable]
		,[bal].[TaxesReceivable]
		,[bal].[DuefromRelatedPartiesCurrent]
		,[bal].[OtherReceivables]
		,[bal].[ReceivablesAdjustmentsAllowances]
		,[bal].[Receivables]
		,[bal].[RawMaterials]
		,[bal].[WorkInProcess]
		,[bal].[FinishedGoods]
		,[bal].[OtherInventories]
		,[bal].[InventoriesAdjustmentsAllowances]
		,[bal].[Inventory]
		,[bal].[PrepaidAssets]
		,[bal].[RestrictedCash]
		,[bal].[CurrentDeferredTaxesAssets]
		,[bal].[CurrentDeferredAssets]
		,[bal].[AssetsHeldForSaleCurrent]
		,[bal].[HedgingAssetsCurrent]
		,[bal].[OtherCurrentAssets]
		,[bal].[CurrentAssets]
		,[bal].[Properties]
		,[bal].[LandAndImprovements]
		,[bal].[BuildingsAndImprovements]
		,[bal].[MachineryFurnitureEquipment]
		,[bal].[OtherProperties]
		,[bal].[ConstructionInProgress]
		,[bal].[Leases]
		,[bal].[GrossPPE]
		,[bal].[AccumulatedDepreciation]
		,[bal].[NetPPE]
		,[bal].[Goodwill]
		,[bal].[OtherIntangibleAssets]
		,[bal].[GoodwillAndOtherIntangibleAssets]
		,[bal].[InvestmentProperties]
		,[bal].[InvestmentsinSubsidiariesatCost]
		,[bal].[InvestmentsinAssociatesatCost]
		,[bal].[InvestmentsInOtherVenturesUnderEquityMethod]
		,[bal].[InvestmentsinJointVenturesatCost]
		,[bal].[LongTermEquityInvestment]
		,[bal].[TradingSecurities]
		,[bal].[FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal]
		,[bal].[AvailableForSaleSecurities]
		,[bal].[HeldToMaturitySecurities]
		,[bal].[InvestmentinFinancialAssets]
		,[bal].[OtherInvestments]
		,[bal].[InvestmentsAndAdvances]
		,[bal].[FinancialAssets]
		,[bal].[NonCurrentAccountsReceivable]
		,[bal].[NonCurrentNoteReceivables]
		,[bal].[DuefromRelatedPartiesNonCurrent]
		,[bal].[NonCurrentDeferredTaxesAssets]
		,[bal].[NonCurrentDeferredAssets]
		,[bal].[NonCurrentPrepaidAssets]
		,[bal].[DefinedPensionBenefit]
		,[bal].[OtherNonCurrentAssets]
		,[bal].[TotalNonCurrentAssets]
		,[bal].[TotalAssets]
		,[bal].[AccountsPayable]
		,[bal].[IncomeTaxPayable]
		,[bal].[TotalTaxPayable]
		,[bal].[DividendsPayable]
		,[bal].[DuetoRelatedPartiesCurrent]
		,[bal].[OtherPayable]
		,[bal].[Payables]
		,[bal].[InterestPayable]
		,[bal].[CurrentAccruedExpenses]
		,[bal].[PayablesAndAccruedExpenses]
		,[bal].[CurrentProvisions]
		,[bal].[PensionandOtherPostRetirementBenefitPlansCurrent]
		,[bal].[CurrentNotesPayable]
		,[bal].[CommercialPaper]
		,[bal].[LineOfCredit]
		,[bal].[OtherCurrentBorrowings]
		,[bal].[CurrentDebt]
		,[bal].[CurrentCapitalLeaseObligation]
		,[bal].[CurrentDebtAndCapitalLeaseObligation]
		,[bal].[CurrentDeferredTaxesLiabilities]
		,[bal].[CurrentDeferredRevenue]
		,[bal].[CurrentDeferredLiabilities]
		,[bal].[OtherCurrentLiabilities]
		,[bal].[CurrentLiabilities]
		,[bal].[LongTermProvisions]
		,[bal].[LongTermDebt]
		,[bal].[LongTermCapitalLeaseObligation]
		,[bal].[LongTermDebtAndCapitalLeaseObligation]
		,[bal].[NonCurrentDeferredTaxesLiabilities]
		,[bal].[NonCurrentDeferredRevenue]
		,[bal].[NonCurrentDeferredLiabilities]
		,[bal].[TradeandOtherPayablesNonCurrent]
		,[bal].[DuetoRelatedPartiesNonCurrent]
		,[bal].[NonCurrentAccruedExpenses]
		,[bal].[NonCurrentPensionAndOtherPostretirementBenefitPlans]
		,[bal].[EmployeeBenefits]
		,[bal].[DerivativeProductLiabilities]
		,[bal].[PreferredSecuritiesOutsideStockEquity]
		,[bal].[RestrictedCommonStock]
		,[bal].[LiabilitiesHeldforSaleNonCurrent]
		,[bal].[OtherNonCurrentLiabilities]
		,[bal].[TotalNonCurrentLiabilitiesNetMinorityInterest]
		,[bal].[TotalLiabilitiesNetMinorityInterest]
		,[bal].[LimitedPartnershipCapital]
		,[bal].[GeneralPartnershipCapital]
		,[bal].[TotalPartnershipCapital]
		,[bal].[PreferredStock]
		,[bal].[CommonStock]
		,[bal].[OtherCapitalStock]
		,[bal].[CapitalStock]
		,[bal].[AdditionalPaidInCapital]
		,[bal].[RetainedEarnings]
		,[bal].[TreasuryStock]
		,[bal].[UnrealizedGainLoss]
		,[bal].[MinimumPensionLiabilities]
		,[bal].[ForeignCurrencyTranslationAdjustments]
		,[bal].[FixedAssetsRevaluationReserve]
		,[bal].[OtherEquityAdjustments]
		,[bal].[GainsLossesNotAffectingRetainedEarnings]
		,[bal].[OtherEquityInterest]
		,[bal].[StockholdersEquity]
		,[bal].[MinorityInterest]
		,[bal].[TotalEquityGrossMinorityInterest]
		,[bal].[TotalCapitalization]
		,[bal].[PreferredStockEquity]
		,[bal].[CommonStockEquity]
		,[bal].[CapitalLeaseObligations]
		,[bal].[NetTangibleAssets]
		,[bal].[WorkingCapital]
		,[bal].[InvestedCapital]
		,[bal].[TangibleBookValue]
		,[bal].[TotalDebt]
		,[bal].[NetDebt]
		,[bal].[ShareIssued]
		,[bal].[OrdinarySharesNumber]
		,[bal].[PreferredSharesNumber]
	FROM [dbo].[STOCK] [stk]
	INNER JOIN [dbo].[BALANCE_SHEET] [bal] ON [stk].[StockID] = [bal].[StockID]
GO

-------------------------------------------------------------------------------------------------
-- Cashflow Satement
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Cash_Flow_Statement]
AS
	SELECT [stk].[StockSymbol]
		,[cash].[ReportDate]
		,[cash].[DomesticSales]
		,[cash].[AdjustedGeographySegmentData]
		,[cash].[FreeCashFlow]
		,[cash].[RepurchaseOfCapitalStock]
		,[cash].[RepaymentOfDebt]
		,[cash].[IssuanceOfDebt]
		,[cash].[IssuanceOfCapitalStock]
		,[cash].[CapitalExpenditure]
		,[cash].[InterestPaidSupplementalData]
		,[cash].[IncomeTaxPaidSupplementalData]
		,[cash].[EndCashPosition]
		,[cash].[OtherCashAdjustmentOutsideChangeinCash]
		,[cash].[BeginningCashPosition]
		,[cash].[EffectOfExchangeRateChanges]
		,[cash].[ChangesInCash]
		,[cash].[OtherCashAdjustmentInsideChangeinCash]
		,[cash].[CashFlowFromDiscontinuedOperation]
		,[cash].[FinancingCashFlow]
		,[cash].[CashFromDiscontinuedFinancingActivities]
		,[cash].[CashFlowFromContinuingFinancingActivities]
		,[cash].[NetOtherFinancingCharges]
		,[cash].[InterestPaidCFF]
		,[cash].[ProceedsFromStockOptionExercised]
		,[cash].[CashDividendsPaid]
		,[cash].[PreferredStockDividendPaid]
		,[cash].[CommonStockDividendPaid]
		,[cash].[NetPreferredStockIssuance]
		,[cash].[PreferredStockPayments]
		,[cash].[PreferredStockIssuance]
		,[cash].[NetCommonStockIssuance]
		,[cash].[CommonStockPayments]
		,[cash].[CommonStockIssuance]
		,[cash].[NetIssuancePaymentsOfDebt]
		,[cash].[NetShortTermDebtIssuance]
		,[cash].[ShortTermDebtPayments]
		,[cash].[ShortTermDebtIssuance]
		,[cash].[NetLongTermDebtIssuance]
		,[cash].[LongTermDebtPayments]
		,[cash].[LongTermDebtIssuance]
		,[cash].[InvestingCashFlow]
		,[cash].[CashFromDiscontinuedInvestingActivities]
		,[cash].[CashFlowFromContinuingInvestingActivities]
		,[cash].[NetOtherInvestingChanges]
		,[cash].[InterestReceivedCFI]
		,[cash].[DividendsReceivedCFI]
		,[cash].[NetInvestmentPurchaseAndSale]
		,[cash].[SaleOfInvestment]
		,[cash].[PurchaseOfInvestment]
		,[cash].[NetInvestmentPropertiesPurchaseAndSale]
		,[cash].[SaleOfInvestmentProperties]
		,[cash].[PurchaseOfInvestmentProperties]
		,[cash].[NetBusinessPurchaseAndSale]
		,[cash].[SaleOfBusiness]
		,[cash].[PurchaseOfBusiness]
		,[cash].[NetIntangiblesPurchaseAndSale]
		,[cash].[SaleOfIntangibles]
		,[cash].[PurchaseOfIntangibles]
		,[cash].[NetPPEPurchaseAndSale]
		,[cash].[SaleOfPPE]
		,[cash].[PurchaseOfPPE]
		,[cash].[CapitalExpenditureReported]
		,[cash].[OperatingCashFlow]
		,[cash].[CashFromDiscontinuedOperatingActivities]
		,[cash].[CashFlowFromContinuingOperatingActivities]
		,[cash].[TaxesRefundPaid]
		,[cash].[InterestReceivedCFO]
		,[cash].[InterestPaidCFO]
		,[cash].[DividendReceivedCFO]
		,[cash].[DividendPaidCFO]
		,[cash].[ChangeInWorkingCapital]
		,[cash].[ChangeInOtherWorkingCapital]
		,[cash].[ChangeInOtherCurrentLiabilities]
		,[cash].[ChangeInOtherCurrentAssets]
		,[cash].[ChangeInPayablesAndAccruedExpense]
		,[cash].[ChangeInAccruedExpense]
		,[cash].[ChangeInInterestPayable]
		,[cash].[ChangeInPayable]
		,[cash].[ChangeInDividendPayable]
		,[cash].[ChangeInAccountPayable]
		,[cash].[ChangeInTaxPayable]
		,[cash].[ChangeInIncomeTaxPayable]
		,[cash].[ChangeInPrepaidAssets]
		,[cash].[ChangeInInventory]
		,[cash].[ChangeInReceivables]
		,[cash].[ChangesInAccountReceivables]
		,[cash].[OtherNonCashItems]
		,[cash].[ExcessTaxBenefitFromStockBasedCompensation]
		,[cash].[StockBasedCompensation]
		,[cash].[UnrealizedGainLossOnInvestmentSecurities]
		,[cash].[ProvisionandWriteOffofAssets]
		,[cash].[AssetImpairmentCharge]
		,[cash].[AmortizationOfSecurities]
		,[cash].[DeferredTax]
		,[cash].[DeferredIncomeTax]
		,[cash].[DepreciationAmortizationDepletion]
		,[cash].[Depletion]
		,[cash].[DepreciationAndAmortization]
		,[cash].[AmortizationCashFlow]
		,[cash].[AmortizationOfIntangibles]
		,[cash].[Depreciation]
		,[cash].[OperatingGainsLosses]
		,[cash].[PensionAndEmployeeBenefitExpense]
		,[cash].[EarningsLossesFromEquityInvestments]
		,[cash].[GainLossOnInvestmentSecurities]
		,[cash].[NetForeignCurrencyExchangeGainLoss]
		,[cash].[GainLossOnSaleOfPPE]
		,[cash].[GainLossOnSaleOfBusiness]
		,[cash].[NetIncomeFromContinuingOperations]
		,[cash].[CashFlowsfromusedinOperatingActivitiesDirect]
		,[cash].[TaxesRefundPaidDirect]
		,[cash].[InterestReceivedDirect]
		,[cash].[InterestPaidDirect]
		,[cash].[DividendsReceivedDirect]
		,[cash].[DividendsPaidDirect]
		,[cash].[ClassesofCashPayments]
		,[cash].[OtherCashPaymentsfromOperatingActivities]
		,[cash].[PaymentsonBehalfofEmployees]
		,[cash].[PaymentstoSuppliersforGoodsandServices]
		,[cash].[ClassesofCashReceiptsfromOperatingActivities]
		,[cash].[OtherCashReceiptsfromOperatingActivities]
		,[cash].[ReceiptsfromGovernmentGrants]
		,[cash].[ReceiptsfromCustomers]
	FROM [dbo].[STOCK] [stk]
	INNER JOIN [dbo].[CASH_FLOW] [cash] ON [stk].[StockID] = [cash].[StockID]
GO

-------------------------------------------------------------------------------------------------
-- View a stock's Price History
-------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[vw_Price_History]
AS
	SELECT [stk].[StockSymbol]
		,[price].[PriceDate]
		,[price].[OpenPrice]
		,[price].[HighPrice]
		,[price].[LowPrice]
		,[price].[ClosePrice]
		,[price].[AdjClosePrice]
		,[price].[Volume]
	FROM [dbo].[STOCK] [stk]
	INNER JOIN [dbo].[PRICE_HISTORY] [price] ON [stk].[StockID] = [price].[StockID]
GO

